"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.videoStatus = exports.videoStatistics = exports.videoSnippet = exports.videoRecordingDetails = exports.videoProcessingDetailsProcessingProgress = exports.videoProcessingDetails = exports.videoPlayer = exports.videoMonetizationDetails = exports.videoLocalization = exports.videoLiveStreamingDetails = exports.videoFileDetailsVideoStream = exports.videoFileDetailsAudioStream = exports.videoFileDetails = exports.videoContentDetailsRegionRestriction = exports.videoContentDetails = exports.videoAgeGating = exports.video = exports.thumbnailDetails = exports.thumbnail = exports.resourceId = exports.propertyValue = exports.playlistStatus = exports.playlistSnippet = exports.playlistPlayer = exports.playlistLocalization = exports.playlistItemStatus = exports.playlistItemSnippet = exports.playlistItemContentDetails = exports.playlistItem = exports.playlistContentDetails = exports.playlist = exports.localizedString = exports.localizedProperty = exports.imageSettings = exports.geoPoint = exports.contentRating = exports.channelTopicDetails = exports.channelStatus = exports.channelStatistics = exports.channelSnippet = exports.channelSettings = exports.channelLocalization = exports.channelConversionPings = exports.channelConversionPing = exports.channelContentOwnerDetails = exports.channelContentDetails = exports.channelBrandingSettings = exports.channelAuditDetails = exports.channel = exports.accessPolicy = void 0;
exports.watchSettings = exports.videoTopicDetails = exports.videoSuggestionsTagSuggestion = exports.videoSuggestions = void 0;
var accessPolicy_1 = require("./accessPolicy");
Object.defineProperty(exports, "accessPolicy", { enumerable: true, get: function () { return __importDefault(accessPolicy_1).default; } });
var channel_1 = require("./channel");
Object.defineProperty(exports, "channel", { enumerable: true, get: function () { return __importDefault(channel_1).default; } });
var channelAuditDetails_1 = require("./channelAuditDetails");
Object.defineProperty(exports, "channelAuditDetails", { enumerable: true, get: function () { return __importDefault(channelAuditDetails_1).default; } });
var channelBrandingSettings_1 = require("./channelBrandingSettings");
Object.defineProperty(exports, "channelBrandingSettings", { enumerable: true, get: function () { return __importDefault(channelBrandingSettings_1).default; } });
var channelContentDetails_1 = require("./channelContentDetails");
Object.defineProperty(exports, "channelContentDetails", { enumerable: true, get: function () { return __importDefault(channelContentDetails_1).default; } });
var channelContentOwnerDetails_1 = require("./channelContentOwnerDetails");
Object.defineProperty(exports, "channelContentOwnerDetails", { enumerable: true, get: function () { return __importDefault(channelContentOwnerDetails_1).default; } });
var channelConversionPing_1 = require("./channelConversionPing");
Object.defineProperty(exports, "channelConversionPing", { enumerable: true, get: function () { return __importDefault(channelConversionPing_1).default; } });
var channelConversionPings_1 = require("./channelConversionPings");
Object.defineProperty(exports, "channelConversionPings", { enumerable: true, get: function () { return __importDefault(channelConversionPings_1).default; } });
var channelLocalization_1 = require("./channelLocalization");
Object.defineProperty(exports, "channelLocalization", { enumerable: true, get: function () { return __importDefault(channelLocalization_1).default; } });
var channelSettings_1 = require("./channelSettings");
Object.defineProperty(exports, "channelSettings", { enumerable: true, get: function () { return __importDefault(channelSettings_1).default; } });
var channelSnippet_1 = require("./channelSnippet");
Object.defineProperty(exports, "channelSnippet", { enumerable: true, get: function () { return __importDefault(channelSnippet_1).default; } });
var channelStatistics_1 = require("./channelStatistics");
Object.defineProperty(exports, "channelStatistics", { enumerable: true, get: function () { return __importDefault(channelStatistics_1).default; } });
var channelStatus_1 = require("./channelStatus");
Object.defineProperty(exports, "channelStatus", { enumerable: true, get: function () { return __importDefault(channelStatus_1).default; } });
var channelTopicDetails_1 = require("./channelTopicDetails");
Object.defineProperty(exports, "channelTopicDetails", { enumerable: true, get: function () { return __importDefault(channelTopicDetails_1).default; } });
var contentRating_1 = require("./contentRating");
Object.defineProperty(exports, "contentRating", { enumerable: true, get: function () { return __importDefault(contentRating_1).default; } });
var geoPoint_1 = require("./geoPoint");
Object.defineProperty(exports, "geoPoint", { enumerable: true, get: function () { return __importDefault(geoPoint_1).default; } });
var imageSettings_1 = require("./imageSettings");
Object.defineProperty(exports, "imageSettings", { enumerable: true, get: function () { return __importDefault(imageSettings_1).default; } });
var localizedProperty_1 = require("./localizedProperty");
Object.defineProperty(exports, "localizedProperty", { enumerable: true, get: function () { return __importDefault(localizedProperty_1).default; } });
var localizedString_1 = require("./localizedString");
Object.defineProperty(exports, "localizedString", { enumerable: true, get: function () { return __importDefault(localizedString_1).default; } });
var playlist_1 = require("./playlist");
Object.defineProperty(exports, "playlist", { enumerable: true, get: function () { return __importDefault(playlist_1).default; } });
var playlistContentDetails_1 = require("./playlistContentDetails");
Object.defineProperty(exports, "playlistContentDetails", { enumerable: true, get: function () { return __importDefault(playlistContentDetails_1).default; } });
var playlistItem_1 = require("./playlistItem");
Object.defineProperty(exports, "playlistItem", { enumerable: true, get: function () { return __importDefault(playlistItem_1).default; } });
var playlistItemContentDetails_1 = require("./playlistItemContentDetails");
Object.defineProperty(exports, "playlistItemContentDetails", { enumerable: true, get: function () { return __importDefault(playlistItemContentDetails_1).default; } });
var playlistItemSnippet_1 = require("./playlistItemSnippet");
Object.defineProperty(exports, "playlistItemSnippet", { enumerable: true, get: function () { return __importDefault(playlistItemSnippet_1).default; } });
var playlistItemStatus_1 = require("./playlistItemStatus");
Object.defineProperty(exports, "playlistItemStatus", { enumerable: true, get: function () { return __importDefault(playlistItemStatus_1).default; } });
var playlistLocalization_1 = require("./playlistLocalization");
Object.defineProperty(exports, "playlistLocalization", { enumerable: true, get: function () { return __importDefault(playlistLocalization_1).default; } });
var playlistPlayer_1 = require("./playlistPlayer");
Object.defineProperty(exports, "playlistPlayer", { enumerable: true, get: function () { return __importDefault(playlistPlayer_1).default; } });
var playlistSnippet_1 = require("./playlistSnippet");
Object.defineProperty(exports, "playlistSnippet", { enumerable: true, get: function () { return __importDefault(playlistSnippet_1).default; } });
var playlistStatus_1 = require("./playlistStatus");
Object.defineProperty(exports, "playlistStatus", { enumerable: true, get: function () { return __importDefault(playlistStatus_1).default; } });
var propertyValue_1 = require("./propertyValue");
Object.defineProperty(exports, "propertyValue", { enumerable: true, get: function () { return __importDefault(propertyValue_1).default; } });
var resourceId_1 = require("./resourceId");
Object.defineProperty(exports, "resourceId", { enumerable: true, get: function () { return __importDefault(resourceId_1).default; } });
var thumbnail_1 = require("./thumbnail");
Object.defineProperty(exports, "thumbnail", { enumerable: true, get: function () { return __importDefault(thumbnail_1).default; } });
var thumbnailDetails_1 = require("./thumbnailDetails");
Object.defineProperty(exports, "thumbnailDetails", { enumerable: true, get: function () { return __importDefault(thumbnailDetails_1).default; } });
var video_1 = require("./video");
Object.defineProperty(exports, "video", { enumerable: true, get: function () { return __importDefault(video_1).default; } });
var videoAgeGating_1 = require("./videoAgeGating");
Object.defineProperty(exports, "videoAgeGating", { enumerable: true, get: function () { return __importDefault(videoAgeGating_1).default; } });
var videoContentDetails_1 = require("./videoContentDetails");
Object.defineProperty(exports, "videoContentDetails", { enumerable: true, get: function () { return __importDefault(videoContentDetails_1).default; } });
var videoContentDetailsRegionRestriction_1 = require("./videoContentDetailsRegionRestriction");
Object.defineProperty(exports, "videoContentDetailsRegionRestriction", { enumerable: true, get: function () { return __importDefault(videoContentDetailsRegionRestriction_1).default; } });
var videoFileDetails_1 = require("./videoFileDetails");
Object.defineProperty(exports, "videoFileDetails", { enumerable: true, get: function () { return __importDefault(videoFileDetails_1).default; } });
var videoFileDetailsAudioStream_1 = require("./videoFileDetailsAudioStream");
Object.defineProperty(exports, "videoFileDetailsAudioStream", { enumerable: true, get: function () { return __importDefault(videoFileDetailsAudioStream_1).default; } });
var videoFileDetailsVideoStream_1 = require("./videoFileDetailsVideoStream");
Object.defineProperty(exports, "videoFileDetailsVideoStream", { enumerable: true, get: function () { return __importDefault(videoFileDetailsVideoStream_1).default; } });
var videoLiveStreamingDetails_1 = require("./videoLiveStreamingDetails");
Object.defineProperty(exports, "videoLiveStreamingDetails", { enumerable: true, get: function () { return __importDefault(videoLiveStreamingDetails_1).default; } });
var videoLocalization_1 = require("./videoLocalization");
Object.defineProperty(exports, "videoLocalization", { enumerable: true, get: function () { return __importDefault(videoLocalization_1).default; } });
var videoMonetizationDetails_1 = require("./videoMonetizationDetails");
Object.defineProperty(exports, "videoMonetizationDetails", { enumerable: true, get: function () { return __importDefault(videoMonetizationDetails_1).default; } });
var videoPlayer_1 = require("./videoPlayer");
Object.defineProperty(exports, "videoPlayer", { enumerable: true, get: function () { return __importDefault(videoPlayer_1).default; } });
var videoProcessingDetails_1 = require("./videoProcessingDetails");
Object.defineProperty(exports, "videoProcessingDetails", { enumerable: true, get: function () { return __importDefault(videoProcessingDetails_1).default; } });
var videoProcessingDetailsProcessingProgress_1 = require("./videoProcessingDetailsProcessingProgress");
Object.defineProperty(exports, "videoProcessingDetailsProcessingProgress", { enumerable: true, get: function () { return __importDefault(videoProcessingDetailsProcessingProgress_1).default; } });
var videoRecordingDetails_1 = require("./videoRecordingDetails");
Object.defineProperty(exports, "videoRecordingDetails", { enumerable: true, get: function () { return __importDefault(videoRecordingDetails_1).default; } });
var videoSnippet_1 = require("./videoSnippet");
Object.defineProperty(exports, "videoSnippet", { enumerable: true, get: function () { return __importDefault(videoSnippet_1).default; } });
var videoStatistics_1 = require("./videoStatistics");
Object.defineProperty(exports, "videoStatistics", { enumerable: true, get: function () { return __importDefault(videoStatistics_1).default; } });
var videoStatus_1 = require("./videoStatus");
Object.defineProperty(exports, "videoStatus", { enumerable: true, get: function () { return __importDefault(videoStatus_1).default; } });
var videoSuggestions_1 = require("./videoSuggestions");
Object.defineProperty(exports, "videoSuggestions", { enumerable: true, get: function () { return __importDefault(videoSuggestions_1).default; } });
var videoSuggestionsTagSuggestion_1 = require("./videoSuggestionsTagSuggestion");
Object.defineProperty(exports, "videoSuggestionsTagSuggestion", { enumerable: true, get: function () { return __importDefault(videoSuggestionsTagSuggestion_1).default; } });
var videoTopicDetails_1 = require("./videoTopicDetails");
Object.defineProperty(exports, "videoTopicDetails", { enumerable: true, get: function () { return __importDefault(videoTopicDetails_1).default; } });
var watchSettings_1 = require("./watchSettings");
Object.defineProperty(exports, "watchSettings", { enumerable: true, get: function () { return __importDefault(watchSettings_1).default; } });
//# sourceMappingURL=index.js.map